### ISSUE TITLE
1.19.2 Crash [?]

### ISSUE THREAD

**Issue by audimatic** [Siphalor/nmuk#15]
[crash-2023-01-09_20.00.47-client.txt](https://github.com/Siphalor/nmuk/files/10375307/crash-2023-01-09_20.00.47-client.txt)

why?

**Comment by NebelNidas** [comment]
It seems like Nmuk for 1.19.2 crashes alongside Fabric API >=0.71.0. Maybe https://github.com/Siphalor/nmuk/commit/12e50a8c0e5bd8a356e91d21d061d4a08ee6302d can be backported?

**Comment by Siphalor** [comment]
Correct, I could reuse that commit, a release is now pushed :)

I had to split off 1.19.2 into a separate branch though, because 1.19-1.19.1 won't receive the Fabric API update.
