### ISSUE TITLE
[1.17] Crash when opening Controls screen

### ISSUE THREAD

**Issue by Leo40Git** [Siphalor/nmuk#3]
Using Amecs API 1.1.5+21w16a on Minecraft 1.17.1.

Crash report: https://pastebin.com/vEB7cFnf

**Comment by Siphalor** [comment]
Well, you're using an outdated version of NMUK :)

Try updating that to 1.0.1+m1.17.1

**Comment by Leo40Git** [comment]
I don't have a dependency on NMUK (I guess Amecs API includes it), but okay I guess?

**Comment by Siphalor** [comment]
oh, true.
Amecs API requires this for testing purposes. Sadly afaik I can't turn that dependency propagation of NMUK off.

So the way to go would probably to exclude NMUK in your build-script:
```gradle
dependencies {
  modImplementation("de.siphalor:amecs-1.17:1.1.5+") {
    exclude module: "nmuk-1.17"
    // or
    transitive false
  }
}
```

**Comment by Leo40Git** [comment]
That's about what I did, yeah. Thanks for the help!
