### ISSUE TITLE
[GitHub] Curseforge link ends in Not Found

### ISSUE THREAD

**Issue by PanoptesDreams** [Siphalor/nmuk#7]
The Curseforge link in the [README.md](https://github.com/Siphalor/nmuk/blob/1.16/README.md) button directs to [here](https://minecraft.curseforge.com/projects/nmuk) resulting in a 404.

![image](https://user-images.githubusercontent.com/55162814/173753083-74e5e2dd-9e68-4262-840a-917d4f3386d7.png)

The correct address is

https://www.curseforge.com/minecraft/mc-mods/nmuk

**Comment by Siphalor** [comment]
Well, that was still using the old CurseForge url ^^

Thanks for bringing it up.

**Comment by Klotzi111** [comment]
Your Amecs repo has the same problem

**Comment by Siphalor** [comment]
> Your Amecs repo has the same problem

Fixed ;)
